spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fornecedor?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
